routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'Web\User\BerandaController@index');
Route::resource('/lokasi', 'Web\User\LokasiController');
Route::resource('/kontak', 'Web\User\KontakController');
Route::post('/pesan/store', 'Web\User\BerandaController@store');

Auth::routes();

Route::resource('/admin/beranda', 'Web\Admin\BerandaController');
Route::resource('/admin/profil', 'Web\Admin\ProfilController');
Route::resource('/admin/gambar', 'Web\Admin\GambarController');
Route::resource('/admin/video', 'Web\Admin\VideoController');
Route::resource('/admin/pesan', 'Web\Admin\PesanController');
Route::resource('/admin/history', 'Web\Admin\HistoryController');

app/Beranda.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Beranda extends Model
{
    protected $guarded = [];
}

app/Http/Controllers/Web/Admin/BerandaController.php
<?php

namespace App\Http\Controllers\Web\Admin;

use App\Beranda;
use App\History;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class BerandaController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $beranda = Beranda::all();
        return view('admin.beranda.beranda', compact('beranda'));
    }

    public function create()
    {
        //
    }

    public function store(Request $request)
    {
        //
    }

    public function show($id)
    {
        //
    }

    public function edit(Beranda $beranda)
    {
        return view('admin.beranda.edit', compact('beranda'));
    }

    public function update(Request $request, Beranda $beranda)
    {
        $beranda->update($request->all());

        // HISTORI
        $histori['user'] = Auth::user()->name;
        $histori['info'] = "Ubah";
        $histori['desc_info'] = "Beranda " . $beranda->beranda_key . " menjadi " . $beranda->beranda_value;
        History::create($histori);

        $notification = array(
            'message' => 'Beranda "' . $beranda->beranda_key . '" berhasil diubah menjadi ' . $beranda->beranda_value,
            'alert-type' => 'success'
        );

        return redirect()->route('beranda.index')->with($notification);
    }

    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Web/User/BerandaController.php
<?php

namespace App\Http\Controllers\Web\User;

use App\Beranda;
use App\Gambar;
use App\History;
use App\Http\Controllers\Controller;
use App\Pesan;
use App\Profil;
use App\Video;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class BerandaController extends Controller
{
    public function index()
    {
        $beranda = Beranda::all();
        $gambar = Gambar::all();
        $profil = Profil::all();
        $video = Video::all();

        return view('user.beranda',compact('beranda','gambar','profil','video'));
    }

    public function create()
    {
        //
    }

    public function store(Request $request)
    {
        $data = $request->only('nama', 'pesan', 'judul', 'email');

        Pesan::create($data);

        // HISTORI
        $histori['user'] = $request->nama;
        $histori['info'] = "Tambah";
        $histori['desc_info'] = "User " . $request->nama . " mengirim pesan " . $request->pesan;
        History::create($histori);

        $notification = array(
            'message' => 'Pesan berhasil dikirim',
            'alert-type' => 'success'
        );

        return redirect()->back()->with($notification);
    }

    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/beranda/beranda.blade.php
@extends('layouts.admin')

@section('content')


<div class="container">

    <section class="content-header">
        <h1>
            Beranda
        </h1>
    </section><br><br>

    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Beranda</h3>
                </div>

                <div class="box-body" style="overflow-x:auto;">
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th>Judul</th>
                                <th>Isi</th>
                                <th>Aksi</th>
                            </tr>
                        </thead>
                        <tbody>

                            @foreach($beranda as $item)
                            <tr>
                                <td>{{ $item->beranda_key }}</td>
                                <td>{!!$item->beranda_value!!}</td>
                                <td align="center">
                                    <a href="{{ route('beranda.edit', $item->id) }}" class="btn btn-primary">Ubah</a>
                                </td>
                            </tr>
                            @endforeach

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/admin/beranda/edit.blade.php
@extends('layouts.admin')

@section('content')

<div class="container">

  <section class="content-header">
    <h1>
      Beranda
    </h1>
  </section><br><br>

  <div class="row">
    <div class="col-md-12">
      <div class="box box-primary">
        <div class="box-header with-border">
          <h3 class="box-title">Edit Beranda</h3>
        </div>
        <form action="{{ route('beranda.update',$beranda->id) }}" class="form-horizontal" method="POST">
          @csrf
          @method('PUT')
          <div class="box-body">
            <div class="form-group">
              <label for="{{$beranda->beranda_key}}" class="col-sm-2 control-label">{{$beranda->beranda_key}}</label>

              <div class="col-sm-10">
                <div class="box-body pad">
                  <textarea name="beranda_value" class="textarea" placeholder="Ketik Disini" style="width: 100%; height: 200px; font-size: 14px; line-height: 18px; border: 1px solid #dddddd; padding: 10px">{{$beranda->beranda_value}}</textarea>
                </div>
              </div>
            </div>
          </div>
          <div class="box-footer">
            <a href="{{url('admin/beranda')}}" class="btn btn-default">Kembali</a>
            <button type="submit" class="btn btn-primary pull-right">Simpan</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
</div>
</div>
@endsection