routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'Web\User\BerandaController@index');
Route::resource('/lokasi', 'Web\User\LokasiController');
Route::resource('/kontak', 'Web\User\KontakController');
Route::post('/pesan/store', 'Web\User\BerandaController@store');

Auth::routes();

Route::resource('/admin/beranda', 'Web\Admin\BerandaController');
Route::resource('/admin/profil', 'Web\Admin\ProfilController');
Route::resource('/admin/gambar', 'Web\Admin\GambarController');
Route::resource('/admin/video', 'Web\Admin\VideoController');
Route::resource('/admin/pesan', 'Web\Admin\PesanController');
Route::resource('/admin/history', 'Web\Admin\HistoryController');

app/Gambar.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Gambar extends Model
{
    protected $guarded = [];
}

app/Http/Controllers/Web/Admin/GambarController.php
<?php

namespace App\Http\Controllers\Web\Admin;

use App\Gambar;
use App\History;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

use Symfony\Component\HttpFoundation\File\UploadedFile;
use File;
use Illuminate\Support\Str;

class GambarController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $data = Gambar::all();
        return view('admin.gambar.beranda', compact('data'));
    }

    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    public function edit(Gambar $gambar)
    {
        return view('admin.gambar.edit', compact('gambar'));
    }

    public function update(Request $request, $id)
    {
        $gambar = Gambar::findOrFail($id);

        $datagambar = $request->only('gambar_key');

        if ($request->hasFile('gambar_value')) {
            $this->deletePhoto($gambar->gambar_value);
            $datagambar['gambar_value'] = $this->savePhoto($request->file('gambar_value'));
        }

        $gambar->update($datagambar);

        // HISTORI
        $histori['user'] = Auth::user()->name;
        $histori['info'] = "Ubah";
        $histori['desc_info'] = "Gambar " . $gambar->gambar_key . " menjadi " . $gambar->gambar_value;
        History::create($histori);

        $notification = array(
            'message' => 'Gambar "' . $gambar->gambar_key . '" berhasil diubah menjadi ' . $gambar->gambar_value,
            'alert-type' => 'success'
        );

        return redirect()->route('gambar.index')->with($notification);
    }

    public function destroy($id)
    {
        //
    }

    protected function savePhoto(UploadedFile $photo)
    {
        $fileName = Str::random(10) . '.' . $photo->guessClientExtension();
        $destinationPath = 'itlabil/images/default';
        $photo->move($destinationPath, $fileName);
        return $fileName;
    }

    public function deletePhoto($filename)
    {
        $path = 'itlabil/images/default/' . $filename;
        return File::delete($path);
    }
}

resources/views/admin/gambar/beranda.blade.php
@extends('layouts.admin')

@section('content')


<div class="container">

    <section class="content-header">
        <h1>
            Gambar
        </h1>
    </section><br><br>

    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Data Gambar</h3>
                </div>

                <div class="box-body" style="overflow-x:auto;">
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th>Judul</th>
                                <th>Isi</th>
                                <th>Aksi</th>
                            </tr>
                        </thead>
                        <tbody>

                            @foreach($data as $item)
                            <tr>
                                <td>{{ $item->gambar_key }}</td>
                                <td><img src="{{asset('itlabil/images/default/'.$item->gambar_value) }}" class="img-thumbnail" width="300px" alt=""></td>
                                <td align="center">
                                    <a href="{{ route('gambar.edit', $item->id) }}" class="btn btn-primary">Ubah</a>
                                </td>
                            </tr>
                            @endforeach

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/admin/gambar/edit.blade.php
@extends('layouts.admin')

@section('content')

<div class="container">

  <section class="content-header">
    <h1>
      Data Gambar
    </h1>
  </section><br><br>

  <div class="row">

    <div class="col-md-4">
      <div class="box box-primary">
        <div class="box-header with-border">
          <h3 class="box-title">Edit Data Gambar</h3>
        </div>
        <form action="{{ route('gambar.update',$gambar->id) }}" class="form-horizontal" method="POST" enctype="multipart/form-data">
          @csrf
          @method('PATCH')
          <div class="box-body">
            <div class="form-group">
              <label for="{{$gambar->gambar_key}}" class="col-sm-4 control-label">{{$gambar->gambar_key}}</label>

              <div class="col-sm-8">
                <input type="file" name="gambar_value" id="cat_image">
              </div>
            </div>
          </div>
          <div class="box-footer">
            <a href="{{url('admin/gambar')}}" class="btn btn-default">Kembali</a>
            <button type="submit" class="btn btn-primary pull-right">Simpan</button>
          </div>
        </form>
      </div>
    </div>

    <div class="col-md-4">
      <div class="box box-primary">
        <div class="box-header with-border">
          <h3 class="box-title">Gambar Sebelumnya</h3>
        </div>
        <div class="box-body">
          <img src="{{asset('itlabil/images/default/'.$gambar->gambar_value) }}" class="img-thumbnail" width="300px" alt="">
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="box box-primary">
        <div class="box-header with-border">
          <h3 class="box-title">Gambar Preview</h3>
        </div>
        <div class="box-body">
          <img src="#" id="category-img-tag" class="img-thumbnail" width="300px" />
        </div>
      </div>
    </div>
  </div>
</div>
</div>
</div>
@endsection