routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'Web\User\BerandaController@index');
Route::resource('/lokasi', 'Web\User\LokasiController');
Route::resource('/kontak', 'Web\User\KontakController');
Route::post('/pesan/store', 'Web\User\BerandaController@store');

Auth::routes();

Route::resource('/admin/beranda', 'Web\Admin\BerandaController');
Route::resource('/admin/profil', 'Web\Admin\ProfilController');
Route::resource('/admin/gambar', 'Web\Admin\GambarController');
Route::resource('/admin/video', 'Web\Admin\VideoController');
Route::resource('/admin/pesan', 'Web\Admin\PesanController');
Route::resource('/admin/history', 'Web\Admin\HistoryController');

app/Profil.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Profil extends Model
{
    protected $guarded = [];
}

app/Http/Controllers/Web/Admin/ProfilController.php
<?php

namespace App\Http\Controllers\Web\Admin;

use App\History;
use App\Http\Controllers\Controller;
use App\Profil;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class ProfilController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $data = Profil::all();
        return view('admin.profil.beranda', compact('data'));
    }

    public function create()
    {
        //
    }

    public function store(Request $request)
    {
        //
    }

    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Profil $profil)
    {
        return view('admin.profil.edit', compact('profil'));
    }

    public function update(Request $request, Profil $profil)
    {
        $profil->update($request->all());

        // HISTORI
        $histori['user'] = Auth::user()->name;
        $histori['info'] = "Ubah";
        $histori['desc_info'] = "Profil " . $profil->profil_key . " menjadi " . $profil->profil_value;
        History::create($histori);

        $notification = array(
            'message' => 'Profil "' . $profil->profil_key . '" berhasil diubah menjadi ' . $profil->profil_value,
            'alert-type' => 'success'
        );

        return redirect()->route('profil.index')->with($notification);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/profil/beranda.blade.php
@extends('layouts.admin')

@section('content')


<div class="container">

    <section class="content-header">
        <h1>
            Profil
        </h1>
    </section><br><br>

    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Data Profil</h3>
                </div>

                <div class="box-body" style="overflow-x:auto;">
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th>Judul</th>
                                <th>Isi</th>
                                <th>Aksi</th>
                            </tr>
                        </thead>
                        <tbody>

                            @foreach($data as $item)
                            <tr>
                                <td>{{ $item->profil_key }}</td>
                                <td>{!!$item->profil_value!!}</td>
                                <td align="center">
                                    <a href="{{ route('profil.edit', $item->id) }}" class="btn btn-primary">Ubah</a>
                                </td>
                            </tr>
                            @endforeach

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/admin/profil/edit.blade.php
@extends('layouts.admin')

@section('content')

<div class="container">

  <section class="content-header">
    <h1>
      Data Profil
    </h1>
  </section><br><br>

  <div class="row">
    <div class="col-md-6">
      <div class="box box-primary">
        <div class="box-header with-border">
          <h3 class="box-title">Edit Data Profil</h3>
        </div>
        <form action="{{ route('profil.update',$profil->id) }}" class="form-horizontal" method="POST">
          @csrf
          @method('PUT')
          <div class="box-body">
            <div class="form-group">
              <label for="{{$profil->profil_key}}" class="col-sm-2 control-label">{{$profil->profil_key}}</label>

              <div class="col-sm-10">
                <input type="text" name="profil_value" value="{{$profil->profil_value}}" class="form-control" placeholder="{{$profil->profil_key}}">
              </div>
            </div>
          </div>
          <div class="box-footer">
            <a href="{{url('admin/profil')}}" class="btn btn-default">Kembali</a>
            <button type="submit" class="btn btn-primary pull-right">Simpan</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
</div>
</div>
@endsection